import urllib
import urllib.parse
from enum import Enum
from typing import List

import requests

from .enums import *
from .flags import *
from .validation import *

BASE_URL = "https://discord.com/api"

DISCORD_EPOCH = 1420070400000


class Snowflake:
    """Creates an object representing a Discord snowflake, providing an interface for accessing properties and performing other operations on these snowflakes."""

    def __init__(self, id: int | str):
        if not isinstance(id, (str, int)):
            raise TypeError("Only accepts integers or strings")

        self._id = int(id) if isinstance(id, str) else id

    @property
    def timestamp(self) -> int:
        """Get the timestamp from the snowflake."""
        return (self._id >> 22) + DISCORD_EPOCH

    @property
    def internal_worker_id(self) -> int:
        """Get the internal worker ID from the snowflake."""
        return (self._id & 0x3E0000) >> 17

    @property
    def internal_process_id(self) -> int:
        """Get the internal process ID from the snowflake."""
        return (self._id & 0x1F000) >> 12

    @property
    def increment(self) -> int:
        """Get the increment from the snowflake."""
        return self._id & 0xFFF

    @classmethod
    def from_timestamp(cls, timestamp_ms: int) -> "Snowflake":
        """Create a snowflake from a unix timestamp."""
        return cls((timestamp_ms - DISCORD_EPOCH) << 22)

    def __eq__(self, other):
        """Compare two snowflakes for equality."""
        if isinstance(other, Snowflake):
            return other._id == self._id
        elif isinstance(other, (int, str)):
            return int(other) == self._id
        return False

    def __ne__(self, other):
        """Compare two snowflakes for inequality."""
        if isinstance(other, Snowflake):
            return other._id != self._id
        elif isinstance(other, (int, str)):
            return int(other) != self._id
        return False

    def __repr__(self) -> str:
        return str(self._id)

    def __str__(self) -> str:
        """Return the string representation of the Snowflake."""
        return str(self._id)


class Message(Schema):
    id: Snowflake | str
    """id of the message"""
    channel_id: Snowflake | str
    """id of the channel the message was sent in"""
    author: "User"
    """the author of this message (not guaranteed to be a valid user, see below)"""
    content: str
    """contents of the message"""
    timestamp: str
    """when this message was sent"""
    edited_timestamp: str = None
    """when this message was edited (or null if never)"""
    tts: bool
    """whether this was a TTS message"""
    mention_everyone: bool
    """whether this message mentions everyone"""
    mentions: list
    """users specifically mentioned in the message"""
    mention_roles: list
    """roles specifically mentioned in this message"""
    mention_channels: list | None
    """channels specifically mentioned in this message"""
    attachments: list
    """any attached files"""
    embeds: list
    """any embedded content"""
    reactions: list | None
    """reactions to the message"""
    nonce: int | str | None
    """used for validating a message was sent"""
    pinned: bool
    """whether this message is pinned"""
    webhook_id: Snowflake | str | None
    """if the message is generated by a webhook, this is the webhook's id"""
    type: MessageTypes | int
    """type of message"""
    activity: object | None
    """sent with Rich Presence-related chat embeds"""
    application: object | None
    """sent with Rich Presence-related chat embeds"""
    application_id: Snowflake | str | None
    """if the message is an Interaction or application-owned webhook, this is the id of the application"""
    message_reference: object | None
    """data showing the source of a crosspost, channel follow add, pin, or reply message"""
    # flags: int | None
    """message flags combined as a bitfield"""
    referenced_message: "Message" | None
    """the message associated with the message_reference"""
    interaction_metadata: object | None
    """In preview. Sent if the message is sent as a result of an interaction"""
    interaction: object | None
    """Deprecated in favor of interaction_metadata; sent if the message is a response to an interaction"""
    thread: "Channel" | None
    """the thread that was started from this message, includes thread member object"""
    components: list | None
    """sent if the message contains components like buttons, action rows, or other interactive components"""
    sticker_items: list | None
    """sent if the message contains stickers"""
    stickers: list | None
    """Deprecated the stickers sent with the message"""
    position: int | None
    """A generally increasing integer (there may be gaps or duplicates) that represents the approximate position of the message in a thread, it can be used to estimate the relative position of the message in a thread in company with total_message_sent on parent thread"""
    role_subscription_data: object | None
    """data of the role subscription purchase or renewal that prompted this ROLE_SUBSCRIPTION_PURCHASE message"""
    resolved: object | None
    """data for users, members, channels, and roles in the message's auto-populated select menus"""
    poll: object | None
    """A poll!"""


class User(Schema):
    """Note: We won't perform any additional validation on names for now, as we can assume Discord has already enforced their rules prior to sending it to us."""

    id: Snowflake | str
    """the user's id"""
    username: str
    """the user's username, not unique across the platform"""
    discriminator: str
    """the user's Discord-tag"""
    global_name: str = None
    """the user's display name, if it is set. For bots, this is the application name"""
    avatar: str = None
    """the user's avatar hash"""
    bot: bool | None
    """whether the user belongs to an OAuth2 application"""
    system: bool | None
    """whether the user is an Official Discord System user (part of the urgent message system)"""
    mfa_enabled: bool | None
    """whether the user has two factor enabled on their account"""
    banner: str | None = None
    """the user's banner hash"""
    accent_color: int | None = None
    """the user's banner color encoded as an integer representation of hexadecimal color code"""
    locale: str | None
    """the user's chosen language option"""
    verified: bool | None
    """whether the email on this account has been verified"""
    email: str | None = None
    """the user's email"""
    flags: UserFlags | int | None
    """the flags on a user's account"""
    premium_type: int | None
    """the type of Nitro subscription on a user's account"""
    public_flags: int | None
    """the public flags on a user's account"""
    avatar_decoration: int | None = None
    """the user's avatar decoration hash"""

    # NOTE The following members are undocumented, but have been observed
    # in the response data from client requests.
    avatar_decoration_data: dict | None = None
    banner_color: str | None = None
    bio: str | None = None
    clan: str | None = None


class Channel(Schema):
    id: Snowflake | str
    type: int
    guild_id: Snowflake | str | None
    position: int | None
    permission_overwrites: list | None
    name: str | None = None
    topic: str | None = None
    nsfw: bool | None
    last_message_id: Snowflake | str | None = None
    bitrate: int | None
    user_limit: int | None
    rate_limit_per_user: int | None
    recipients: list | None
    icon: str | None = None
    owner_id: Snowflake | str | None
    application_id: Snowflake | str | None
    managed: bool | None
    parent_id: Snowflake | str | None = None
    last_pin_timestamp: str | None = None
    rtc_region: str | None = None
    video_quality_mode: int | None
    message_count: int | None
    member_count: int | None
    # thread_metadata: None # TODO
    # member: None # TODO
    default_auto_archive_duration: int | None
    permissions: str | None
    flags: int | None
    total_message_sent: int | None
    available_tags: list | None
    applied_tags: list | None
    # default_reaction_emoji: None # TODO
    default_thread_rate_limit_per_user: int | None
    default_sort_order: int | None = None
    default_forum_layout: int | None

    client: "Client"

    def get_channel_messages(
        self,
        around: Snowflake = None,
        before: Snowflake = None,
        after: Snowflake = None,
        limit: int = 50,
    ) -> List[Message]:
        if 1 > limit < 100:
            raise ValueError("limit parameter is out of bounds")

        params_dict = {"limit": limit}

        if around:
            params_dict["around"] = around
        if before:
            params_dict["before"] = before
        if after:
            params_dict["after"] = after

        response = self._get("/users/@me/guilds", params_dict)

        return [Guild(guild) for guild in response] if response else None


class GuildMemberObject(Schema):
    user: User | dict | None
    nick: str | None = None
    avatar: str | None = None
    roles: list  # TODO
    joined_at: str
    premium_since: str | None = None
    deaf: bool
    mute: bool
    flags: GuildMemberFlags | int
    pending: bool | None
    permissions: str | None
    communication_disabled_until: str | None = None
    unusual_dm_activity_until: str | None = None  # NOTE undocumented


class Guild(Schema):
    id: Snowflake | str
    name: str
    icon: str = None
    icon_hash: str | None = None
    splash: str = None
    discover_splash: str = None
    owner: bool = False
    owner_id: Snowflake | str
    permissions: str | None
    region: str | None = None
    afk_channel_id: Snowflake | str = None
    afk_timeout: int
    widget_enabled: bool | None
    widget_channel_id: Snowflake | None = None
    verification_level: VerificationLevel | int
    default_message_notifications: DefaultMessageNotificationLevel | int
    explicit_content_filter: ExplicitContentFilterLevel | int
    # roles: None # TODO
    # emojis: None # TODO
    # features: None # TODO
    mfa_level: MFALevel | int
    application_id: Snowflake | str = None
    system_channel_id: Snowflake | str = None
    system_channel_flags: SystemChannelFlags | int
    rules_channel_id: Snowflake | str = None
    max_presences: int | None = None
    max_members: int | None
    vanity_url_code: str = None
    description: str = None
    banner: str = None
    premium_tier: PremiumTier | int
    premium_subscription_count: int | None
    preferred_locale: str
    public_updates_channel_id: Snowflake | str = None
    max_video_channel_users: int | None
    max_stage_video_channel_users: int | None
    approximate_member_count: int | None
    approximate_presence_count: int | None
    # welcome_screen: None # TODO
    nsfw_level: GuildNSFWLevel | int
    # stickers: None # TODO
    premium_progress_bar_enabled: bool
    safety_alerts_channel_id: Snowflake | str = None


class ConnectionObject(Schema):
    id: Snowflake | str
    name: str
    type: ConnectionServices | str
    revoked: bool | None
    intergations: list  # TODO
    verified: bool
    friend_sync: bool
    show_activity: bool
    two_way_link: bool
    visibility: int


class GuildPreview(Schema):
    id: Snowflake | str
    name: str
    icon: str = None
    splash: str = None
    discovery_splash: str = None
    emojis: list
    features: list
    approximate_member_count: int
    approximate_presence_count: int
    description: str = None
    stickers: list


class GuildDiscovery(Schema):
    """This structure lacks documentation."""

    id: Snowflake | str
    approximate_member_count: int
    approximate_presence_count: int
    auto_removed: bool
    banner: str
    description: str
    discovery_splash: str
    features: list
    icon: str
    is_published: bool
    keywords: list
    name: str
    preferred_locale: str
    premium_subscription_count: int
    primary_category_id: int
    splash: str
    vanity_url_code: str


class Client:
    def __init__(self, token, api_version: int = 9):
        self.requests_session = requests.Session()
        self.api_version = api_version
        self.token = token

        self.headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/123.0",
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate, br",
            "Authorization": token,
            "X-Discord-Locale": "en-US",
            "X-Discord-Timezone": "America/New_York",
            "X-Super-Properties": "eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiRmlyZWZveCIsImRldmljZSI6IiIsInN5c3RlbV9sb2NhbGUiOiJlbi1VUyIsImJyb3dzZXJfdXNlcl9hZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQ7IHJ2OjEwOS4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzEyMy4wIiwiYnJvd3Nlcl92ZXJzaW9uIjoiMTIzLjAiLCJvc192ZXJzaW9uIjoiMTAiLCJyZWZlcnJlciI6Imh0dHBzOi8vZGlzY29yZC5jb20vIiwicmVmZXJyaW5nX2RvbWFpbiI6ImRpc2NvcmQuY29tIiwicmVmZXJyZXJfY3VycmVudCI6IiIsInJlZmVycmluZ19kb21haW5fY3VycmVudCI6IiIsInJlbGVhc2VfY2hhbm5lbCI6InN0YWJsZSIsImNsaWVudF9idWlsZF9udW1iZXIiOjI3Nzk1MywiY2xpZW50X2V2ZW50X3NvdXJjZSI6bnVsbH0=",
            "Alt-Used": "discord.com",
        }

    def _get(self, url, params):
        response = self.requests_session.get(
            url=f"{BASE_URL}/v{self.api_version}{url}",
            params=params,
            headers=self.headers,
        )

        return response.json() if response.status_code == 200 else None

    def get_current_user_connections(self) -> ConnectionObject:
        """GET /users/@me/connections"""
        pass

    def get_current_user_guild_member(self):
        pass

    def get_channel(self, guild_id: Snowflake) -> Channel:
        response = self._get(f"/channels/{guild_id}")

        return Channel(response, client=self) if response else None

    def get_current_user_guilds(
        self,
        before: Snowflake = None,
        after: Snowflake = None,
        limit: int = 200,
        with_counts: bool = False,
    ) -> List[Guild]:
        if 1 > limit < 200:
            raise ValueError("limit parameter is out of bounds")

        params_dict = {"limit": limit, "with_counts": with_counts}

        if before:
            params_dict["before"] = before
        if after:
            params_dict["after"] = after

        response = self._get("/users/@me/guilds", params_dict)

        return [Guild(guild) for guild in response] if response else None

    def get_discoverable_guilds(
        self, offset: int = 0, limit: int = 30
    ) -> List[GuildDiscovery]:
        # https://discord.com/api/v9/discoverable-guilds?offset=0&limit=30
        params_dict = {"offset": offset, "limit": limit}

        response = self._get("/discoverable-guilds", params_dict)

        return (
            [GuildDiscovery(guild) for guild in response["guilds"]]
            if response
            else None
        )

    def get_current_user(self) -> User:
        pass

    def get_user(self, id: Snowflake) -> User:
        pass
